{% set name = "qca" %}
{% set version = "2.1.1" %}
{% set md5 = "55dcd05bc05f431184e97537dadda694" %}

package:
  name: qca
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/KDE/qca/archive/v{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - cmake
    - pkg-config  # [unix]
    - qt 4.8.*
  run:
    - qt 4.8.*
 
test:
  commands:
    - test -f ${PREFIX}/lib/libqca.so  # [linux]
    - test -d ${PREFIX}/lib/qca.framework  # [osx]

about:
  home: http://delta.affinix.com/qca/ 
  license: LGPL-2.1
  license_file: COPYING
  summary: Qt Cryptographic Architecture (QCA) provides a straightforward and cross-platform crypto API, using Qt datatypes and conventions. 
  description: |
    Taking a hint from the similarly-named Java Cryptography Architecture, QCA
    aims to provide a straightforward and cross-platform crypto API, using Qt
    datatypes and conventions. QCA separates the API from the implementation,
    using plugins known as Providers. The advantage of this model is to allow
    applications to avoid linking to or explicitly depending on any particular
    cryptographic library. This allows one to easily change or upgrade crypto
    implementations without even needing to recompile the application! QCA
    should work everywhere Qt does, including Windows/Unix/MacOSX.
  doc_url: http://delta.affinix.com/docs/qca/
  dev_url: https://quickgit.kde.org/?p=qca.git

extra:
  recipe-maintainers:
    - ceholden
